realm_ai:
  behavior_name: 3DBallHard
  algorithm: grid

mlagents:
  env_settings:
    env_path: ../../../Unity/envs/3dball/3dball
    env_args: null
    num_envs: 4
    seed: 0

  engine_settings:
    no_graphics: true
  
  checkpoint_settings:
    # run_id: anything # does not matter, will be generated automatically
    initialize_from: null
    load_model: false
    resume: false
    force: false
    inference: false

  # torch_settings:
  #   device: cpu

  default_settings:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 12000
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000
    time_horizon: 1000
    summary_freq: 5000