realm_ai:
  behavior_name: 3DBallHard
  algorithm: bayes # or random
  total_trials: 3 # total number of trials (inclusive of warmup_trials)
  warmup_trials: 5 # optional for bayes algorithm, number of "warmup" trials where random hyperparams are used. Default val is 5
  eval_window_size: 1 # optional, training run is evaluated by taking the average eps rew of past x episodes. Default val is 1
  folder_name: test # optional, specify to manually specify folder name, or to continue running
  full_run_after_tuning: # optional, if specified, config in "best_trial" folder will be changed to reflect the following. If this is specified, run_id should be specified so that we know the name of the folder!
    max_steps: 20000 # number of steps to run for the full training
    run_id: full_run # name of the complete training run
  wandb_project: realm_tune # optional, if specified, log training metrics to wandb

mlagents: # all values here (even those that are commented out) are used by the script. Other possible configs that are not here can be added at the discretion of the user.
  env_settings:
    env_path: ../../../../../Unity/envs/3dball/3dball
    env_args: null
    num_envs: 4
    seed: 0

  engine_settings:
    no_graphics: true
  
  # checkpoint_settings: 
  #   run_id: anything # does not matter, will be generated automatically
  #   force: false # does not matter, overwritten as True through cli argument

  # torch_settings:
  #   device: cpu

  default_settings:
    trainer_type: ppo
    hyperparameters:
      batch_size: [64, 128, 256] # Means categorical
      buffer_size: log_unif(2000, 12000) # Automatic detection as int
      learning_rate: log_unif(0.0003, 0.01) # Automatic detection as float
      beta: log_unif(0.001, 0.01) # unif and log_unif exclude upper bound - [0.001, 0.01)
      epsilon: 0.2
      lambd: 0.99
      num_epoch: unif(1, 15)
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: [0.99, 0.95]
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000
    time_horizon: 1000
    summary_freq: 5000